<?php 

return [
    1 => [
        "name" => "Startnod navigering",
        "description" => "Start node main menu",
        "key" => "navStartNode",
        "type" => "document",
        "data" => "",
        "config" => "",
        "ctype" => "document",
        "inheritable" => "1",
        "creationDate" => "0",
        "modificationDate" => "0",
        "id" => "1"
    ],
    6 => [
        "name" => "Sidansvarig",
        "description" => "Sidansvarig",
        "key" => "pageManager",
        "type" => "text",
        "data" => "",
        "config" => "",
        "ctype" => "document",
        "inheritable" => "1",
        "creationDate" => "0",
        "modificationDate" => "0",
        "id" => "6"
    ],
    9 => [
        "name" => "Mall",
        "description" => "Fakultets- eller institutionswebb",
        "key" => "templateType",
        "type" => "select",
        "data" => "department",
        "config" => "department, faculty, internal",
        "ctype" => "document",
        "inheritable" => "1",
        "creationDate" => "0",
        "modificationDate" => "0",
        "id" => "9"
    ],
    12 => [
        "id" => 12,
        "name" => "Sektionstitel",
        "description" => "Namn på undersajt",
        "key" => "section",
        "type" => "text",
        "data" => NULL,
        "config" => NULL,
        "ctype" => "document",
        "inheritable" => TRUE,
        "creationDate" => 1542207452,
        "modificationDate" => 1542207452
    ],
    14 => [
        "id" => 14,
        "name" => "Utbildningspresentation: anmälningskod (LU-18XXX)",
        "description" => "Kod för ansökan (LU-18XXX)",
        "key" => "code",
        "type" => "text",
        "data" => NULL,
        "config" => NULL,
        "ctype" => "document",
        "inheritable" => TRUE,
        "creationDate" => 1542207655,
        "modificationDate" => 1592896706
    ],
    22 => [
        "name" => "Sida med specialtitel",
        "description" => "För sidor med tabbad navigering",
        "key" => "tabPageTitle",
        "type" => "bool",
        "data" => "1",
        "config" => NULL,
        "ctype" => "document",
        "inheritable" => "1",
        "creationDate" => "0",
        "modificationDate" => "0",
        "id" => "22"
    ],
    23 => [
        "id" => 23,
        "name" => "Utbildningspresentation: sidtitel",
        "description" => "Sidtitel",
        "key" => "tabTitle",
        "type" => "text",
        "data" => NULL,
        "config" => NULL,
        "ctype" => "document",
        "inheritable" => TRUE,
        "creationDate" => 1542207583,
        "modificationDate" => 1542207583
    ],
    24 => [
        "id" => 24,
        "name" => "Utbildningspresentation: undertitel",
        "description" => "Undertitel",
        "key" => "tabSubTitle",
        "type" => "text",
        "data" => NULL,
        "config" => NULL,
        "ctype" => "document",
        "inheritable" => TRUE,
        "creationDate" => 1542207599,
        "modificationDate" => 1542207599
    ],
    25 => [
        "id" => 25,
        "name" => "Utbildningspresentation: ansökan öppen",
        "description" => "",
        "key" => "apply1",
        "type" => "bool",
        "data" => "1",
        "config" => NULL,
        "ctype" => "document",
        "inheritable" => TRUE,
        "creationDate" => 1542207619,
        "modificationDate" => 1542207628
    ],
    30 => [
        "id" => 30,
        "name" => "Bild i sociala medier",
        "description" => "",
        "key" => "social_media_image",
        "type" => "asset",
        "data" => "",
        "config" => "",
        "ctype" => "document",
        "inheritable" => FALSE,
        "creationDate" => 1487599816,
        "modificationDate" => 1552040406
    ],
    31 => [
        "id" => 31,
        "name" => "Utbildningspresentation: bild",
        "description" => "Långsmal bild sidhuvud",
        "key" => "tabHero",
        "type" => "asset",
        "data" => NULL,
        "config" => NULL,
        "ctype" => "document",
        "inheritable" => TRUE,
        "creationDate" => 1542207480,
        "modificationDate" => 1592896804
    ],
    32 => [
        "id" => 32,
        "name" => "Visa ej sidansvarig",
        "description" => "",
        "key" => "DontShowPageManager",
        "type" => "bool",
        "data" => "1",
        "config" => "",
        "ctype" => "document",
        "inheritable" => TRUE,
        "creationDate" => 1542207724,
        "modificationDate" => 1542207862
    ],
    33 => [
        "id" => 33,
        "name" => "Toolbar-titel",
        "description" => "Alt.titel i toolbar",
        "key" => "toolbarTitle",
        "type" => "text",
        "data" => NULL,
        "config" => NULL,
        "ctype" => "document",
        "inheritable" => FALSE,
        "creationDate" => 1588232296,
        "modificationDate" => 1588232321
    ]
];
